# Generated by Django 5.1.2 on 2024-11-11 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servapp', '0002_tasks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='taskuser',
            new_name='user',
        ),
    ]
